kumuluzee:
  name: users
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  discovery:
    etcd:
      hosts: http://192.168.29.109:2379
  #metrics:
  #  web-instrumentation:
  #    - name: userss-endpoint
  #      url-pattern: /v1/users/*
  #logs:
  #  config-file: '<?xml version="1.0" encoding="UTF-8"?>
  #                    <Configuration name="users">
  #                        <Appenders>
  #                            <Console name="console" target="SYSTEM_OUT">
  #                                <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
  #                            </Console>
  #                            <Socket name="logstash" host="0a8a4c34-9be9-42b7-bf06-6a99a9d827c0-ls.logit.io"
  #                            port="16488" protocol="tcp">
  #                                <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
  #                            </Socket>
  #                        </Appenders>
  #                        <Loggers>
  #                            <!-- Default logger -->
  #                            <Root level="all">
  #                                <AppenderRef ref="console" level="info"/>
  #                                <AppenderRef ref="logstash" level="trace"/>
  #                            </Root>
  #                        </Loggers>
  #                    </Configuration>'
