apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: rsoteam8/users:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              name: server
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: users
spec:
  type: ClusterIP
  ports:
    - port: 8081
      protocol: TCP
      targetPort: server
  selector:
    app: users

